{
 "title": "Shorten-url-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Histogram - path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(urlshortener_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram - requests speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(urlshortener_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shorten rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(urlshortener_shortens_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirects_total + queue len",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(urlshortener_redirects_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "urlshortener_click_queue_depth", "legendFormat": "__auto" }
   ]
  }
 ]
}