name: URL-CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Golang
        uses: actions/setup-go@v6
        with: 
          go-version-file: go.mod
          cache-dependency-path: 'go.sum'

      - name: Go build
        run: go build ./...

      - name: Go vet
        run: go vet ./...

      - name: Go test 
        run: go test ./...